---
title: "shapefile experimenting"
author: "Jimmy Choi"
date: "2025-01-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "")
library(sf)
library(ggplot2)
library(tidyverse)
library(plyr)
library(rnaturalearth)
```

```{r}
## shapefiles are from TetrapodTraits, Moura et al. (2024)
## paper DOI: 10.1371/journal.pbio.3002658
## database DOI: 10.5281/zenodo.10530617
```

```{r}
tetrapodtraits.shapefile <- read_sf("GridCellShapefile/Shapefiles/gridcells_110km.shp")
tetrapodtraits.shapefile
```

```{r}
tetrapod360 <- read.csv("Tetrapod_360.csv")
tetrapod360$Scientific.Name <- mapvalues(tetrapod360$Scientific.Name, from = c("Herpestes brachyurus", "Herpestes edwardsii", "Herpestes fuscus", "Herpestes javanicus", "Herpestes naso", "Herpestes semitorquatus", "Herpestes smithii", "Herpestes urva", "Herpestes vitticollis"), to = c("Urva brachyura", "Urva edwardsii", "Urva fusca", "Urva javanica", "Xenogale naso", "Urva semitorquata", "Urva smithii", "Urva urva", "Urva vitticollis"))
herp.cells <- tetrapod360[which(tetrapod360$Scientific.Name %in% tetrapodtraits.herp$Scientific.Name),]
herp.cells
```

```{r}
herp.range <- tetrapodtraits.shapefile %>%
  filter(Cl_I110 %in% herp.cells$Cell_Id110)
variant.herp <- variant.mamm$X.2[31:39]
variant.herp <- mapvalues(variant.herp, from = c("Urva edwardsi"), to = c("Urva edwardsii"))
tetrapod360.variant.herp <- herp.cells[which(herp.cells$Scientific.Name %in% variant.herp),]
variant.herp.range <- tetrapodtraits.shapefile %>%
  filter(Cl_I110 %in% tetrapod360.variant.herp$Cell_Id110)
```

```{r}
ne_sf <- ne_countries(returnclass = "sf")

ggplot(data = ne_sf) +
  geom_sf(color = "black", aes(fill = "white")) +
  geom_sf(data = herp.range, aes(fill = "grey", colour = NA)) +
  geom_sf(data = variant.herp.range, aes(fill = "#D55E00", colour = NA), alpha = 1) +
  scale_fill_identity(name = '', guide = 'legend', labels = c("Variant species present", "Only XX/XY present", "Not present")) +
  scale_colour_identity(name = '', guide = 'none', labels = c("Variant species present", "Only XX/XY present", "Not present")) +
  theme_void()

#"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2"
#"#D55E00" "#CC79A7" "#999999" Okabe colors
```





```{r}
tetrapod360$Scientific.Name <- mapvalues(tetrapod360$Scientific.Name, from=c("Dermanura aztecus", "Dermanura cinereus", "Dermanura glaucus", "Dermanura gnomus", "Dermanura rosenbergii", "Dermanura toltecus", "Lophostoma aequatorialis", "Lophostoma silvicolum", "Mimon crenulatum", "Mimon koepckeae", "Vampyressa bidens", "Vampyressa brocki", "Vampyressa nymphaea", "Diaemus youngi"), to=c("Dermanura azteca", "Dermanura cinerea", "Dermanura glauca", "Dermanura gnoma", "Dermanura rosenbergi", "Dermanura tolteca", "Lophostoma occidentale", "Lophostoma silvicola", "Gardnerycteris crenulata", "Gardnerycteris koepckeae", "Vampyriscus bidens", "Vampyriscus brocki", "Vampyriscus nymphaeus", "Diaemus youngii"))
phyllo.cells <- tetrapod360[which(tetrapod360$Scientific.Name %in% tetrapodtraits.phyllostom$Scientific.Name),]
phyllo.cells
```

```{r}
phyllo.range <- tetrapodtraits.shapefile %>%
  filter(Cl_I110 %in% phyllo.cells$Cell_Id110)
```

```{r}
variant.phyllo <- variant.mamm$X.2[40:69]
tetrapod360.variant.phyllo <- phyllo.cells[which(phyllo.cells$Scientific.Name %in% variant.phyllo),]
variant.phyllo.range <- tetrapodtraits.shapefile %>%
  filter(Cl_I110 %in% tetrapod360.variant.phyllo$Cell_Id110)
```

```{r}
ne_sf <- ne_countries(returnclass = "sf")

ggplot(data = ne_sf) +
  geom_sf(color = "black", aes(fill = "white")) +
  geom_sf(data = phyllo.range, aes(fill = "grey", colour = NA)) +
  geom_sf(data = variant.phyllo.range, aes(fill = "#CC79A7", colour = "#CC79A7")) +
  scale_fill_identity(name = '', guide = 'legend', labels = c("Variant species present", "Only XX/XY present", "Not present")) +
  scale_colour_identity(name = '', guide = 'none', labels = c("Variant species present", "Only XX/XY present", "Not present")) +
  theme_void()

#"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2"
#"#D55E00" "#CC79A7" "#999999" Okabe colors
```

```{r}
phyllostom.XAYA <- tetrapodtraits.phyllostom$Scientific.Name[tetrapodtraits.phyllostom$sex == "XAYAfusion"]
phyllostom.XA <- tetrapodtraits.phyllostom$Scientific.Name[tetrapodtraits.phyllostom$sex == "XAfusion"]
tetrapod360.XAYA.phyllo <- phyllo.cells[which(phyllo.cells$Scientific.Name %in% phyllostom.XAYA),]
XAYA.phyllo.range <- tetrapodtraits.shapefile %>%
  filter(Cl_I110 %in% tetrapod360.XAYA.phyllo$Cell_Id110)
tetrapod360.XA.phyllo <- phyllo.cells[which(phyllo.cells$Scientific.Name %in% phyllostom.XA),]
XA.phyllo.range <- tetrapodtraits.shapefile %>%
  filter(Cl_I110 %in% tetrapod360.XA.phyllo$Cell_Id110)
phyllo.cells.both.variant <- intersect(XA.phyllo.range$Cl_I110, XAYA.phyllo.range$Cl_I110)
both.variant.phyllo.range <- phyllo.range[phyllo.range$Cl_I110 %in% phyllo.cells.both.variant, ]
```

```{r}
ne_sf <- ne_countries(returnclass = "sf")

ggplot(data = ne_sf) +
  geom_sf(color = "black", aes(fill = "white")) +
  geom_sf(data = phyllo.range, aes(fill = "grey", colour = NA)) +
  geom_sf(data = XAYA.phyllo.range, aes(fill = "#CC79A7", colour = NA), alpha = 1) +
  geom_sf(data = XA.phyllo.range, aes(fill = "#56B4E9", colour = NA), alpha = 1) +
  geom_sf(data = both.variant.phyllo.range, aes(fill = "#E69F00", colour = NA), alpha = 1) +
  scale_fill_identity(name = '', guide = 'legend', labels = c("XAfusion species present", "XAYAfusion species present", "Both variant types present", "Only XX/XY present", "Not present")) +
  scale_colour_identity(name = '', guide = 'none', labels = c("XAfusion species present", "XAYAfusion species present", "Both variant types present", "Only XX/XY present", "Not present")) +
  theme_void()

#"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2"
#"#D55E00" "#CC79A7" "#999999" Okabe colors
# plot background world map with only outline, use gray as XX/XY
```





```{r}
sorex.cells <- tetrapod360[which(tetrapod360$Scientific.Name %in% tetrapodtraits.sorex$Scientific.Name),]
sorex.cells
```

```{r}
sorex.range <- tetrapodtraits.shapefile %>%
  filter(Cl_I110 %in% sorex.cells$Cell_Id110)
```

```{r}
variant.shrew <- variant.mamm$X.2[77:86]
tetrapod360.variant.shrew <- sorex.cells[which(sorex.cells$Scientific.Name %in% variant.shrew),]
variant.shrew.range <- tetrapodtraits.shapefile %>%
  filter(Cl_I110 %in% tetrapod360.variant.shrew$Cell_Id110)
```

```{r}
ne_sf <- ne_countries(returnclass = "sf")

ggplot(data = ne_sf) +
  geom_sf(color = "black", aes(fill = "white")) +
  geom_sf(data = sorex.range, aes(fill = "grey", colour = NA)) +
  geom_sf(data = variant.shrew.range, aes(fill = "#56B4E9", colour = NA), alpha = 0.7) +
  scale_fill_identity(name = '', guide = 'legend', labels = c("Variant species present", "Only XX/XY present", "Not present")) +
  scale_colour_identity(name = '', guide = 'none', labels = c("Variant species present", "Only XX/XY present", "Not present"))  +
  theme_void()

#"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2"
#"#D55E00" "#CC79A7" "#999999" Okabe colors
#add.alpha for transparency?
```
